// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgTVPMCUXTlvgevlIOsk8sybuZj9zv0DY',
    appId: '1:570997935258:web:59e49d99585f3d60b02323',
    messagingSenderId: '570997935258',
    projectId: 'act13-29757',
    authDomain: 'act13-29757.firebaseapp.com',
    storageBucket: 'act13-29757.firebasestorage.app',
    measurementId: 'G-ZZB99GZ4FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOzS3hZXSY24MlfuA6hY7rILs92gYOdks',
    appId: '1:570997935258:android:af1e6a24192ed82cb02323',
    messagingSenderId: '570997935258',
    projectId: 'act13-29757',
    storageBucket: 'act13-29757.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVTvZVnZPgDtjcQytPWNnxdLijirvE4wI',
    appId: '1:570997935258:ios:a422f763c27ffdebb02323',
    messagingSenderId: '570997935258',
    projectId: 'act13-29757',
    storageBucket: 'act13-29757.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVTvZVnZPgDtjcQytPWNnxdLijirvE4wI',
    appId: '1:570997935258:ios:a422f763c27ffdebb02323',
    messagingSenderId: '570997935258',
    projectId: 'act13-29757',
    storageBucket: 'act13-29757.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgTVPMCUXTlvgevlIOsk8sybuZj9zv0DY',
    appId: '1:570997935258:web:e6d9d507ed7c4500b02323',
    messagingSenderId: '570997935258',
    projectId: 'act13-29757',
    authDomain: 'act13-29757.firebaseapp.com',
    storageBucket: 'act13-29757.firebasestorage.app',
    measurementId: 'G-L73R21M1W2',
  );
}
